[versions]
jdbi3 = "3.50.0"
junit = "6.0.1"
testcontainers-core = "2.0.2"
testcontainers = "1.21.3"

hikariCP = "7.0.2"
postgresql = "42.7.8"
mysql = "9.5.0"

slf4j = "2.0.17"
logback = "1.5.21"
spring-boot = "3.5.0"

[libraries]
jdbi3-core = { module = "org.jdbi:jdbi3-core", version.ref = "jdbi3" }
jdbi3-sqlobject = { module = "org.jdbi:jdbi3-sqlobject", version.ref = "jdbi3" }
jdbi3-jackson2 = { module = "org.jdbi:jdbi3-jackson2", version.ref = "jdbi3" }
jdbi3-postgres = { module = "org.jdbi:jdbi3-postgres", version.ref = "jdbi3" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher"}
hikariCP = { module = "com.zaxxer:HikariCP", version.ref = "hikariCP" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
mysql = { module = "com.mysql:mysql-connector-j", version.ref = "mysql" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers-core" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainers-mysql = { module = "org.testcontainers:mysql", version.ref = "testcontainers" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "spring-boot" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "spring-boot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }
spring-jdbc = { module = "org.springframework:spring-jdbc", version = "6.2.7" }
spring-tx = { module = "org.springframework:spring-tx", version = "6.2.7" }

[bundles]
testcontainers-all = [
    "testcontainers",
    "testcontainers-junit-jupiter",
    "testcontainers-postgresql",
    "testcontainers-mysql"
]

junit-all = [
    "junit-jupiter",
    "junit-platform-launcher"
]

database-drivers = [
    "postgresql",
    "mysql"
]

[plugins]
